FROM node:20-alpine


RUN apk update && apk add --no-cache openssl

WORKDIR /app

# Copy shared files
COPY utils ./utils/
COPY db ./db/
# Copy worker files 
COPY worker/package*.json ./worker/
COPY worker/tsconfig.json ./worker/
COPY worker/src ./worker/src/

WORKDIR /app/worker

# Install dependencies
RUN npm install

RUN npx prisma generate 

RUN npm run build

CMD ["node", "dist/worker/src/index.js"] 